### ISSUE TITLE
README example looks out of date, and it would be great to have a hello world example

### ISSUE THREAD

**Issue by apatil** [timbertson/opam2nix-packages#2]
Hi @timbertson, this looks really promising. I've been experimenting with standard opam development, which forces me to give up Nix's advantages; and with the NixOS ocamlPackages, which force me to give up opam's smart version solver. It looks like opam2nix is trying to provide the best of both worlds.

The example in the readme,
```ocaml
let
  pkgs = import ../nixpkgs {};
  opam2nix = import ../opam2nix-packages { inherit pkgs; };
  buildInputs = opam2nix.build { packages = ["lwt"]; };
```
doesn't seem to work because `opam2nix` as written is a function, so `opam2nix.build` is a type error. Also, it would be really helpful to have a hello world example in the source tree that shows me how to develop with opam2nix.

**Comment by timbertson** [comment]
Thanks for your enthusiasm :)

I'm still treading the fine line of deciding whether the current system works well enough to try and push more officially, or whether it needs more simplifying before it can be widely used. But actually having more people use it and give feedback would certanly help, so I'll try and get the README (and an example) working fairly soon.

**Comment by timbertson** [comment]
OK, I've added one example in https://github.com/timbertson/opam2nix-packages/tree/master/examples - please let me know if you have trouble getting started with that. I have another example planned as you can see there, but it might need more code before it's in a publishable state.

I didn't find much incorrect with the readme, although I can see where issues might arise - in order to use opam2nix, you should copy/reference the `nix/release.nix` file, not try to import the opam2nix-packages `default.nix`. I've actually removed this file now, as it stopped being buildable sometime ago and I hadn't noticed.

**Comment by apatil** [comment]
It worked, thanks! Looking forward to the opam package development example. I'll try to understand how opam2nix works in the meantime.

**Comment by timbertson** [comment]
And now the package development example is up too! It actually was way easier than I was fearing, which is awesome 🎉 (there could be some rough edges though) . I should start using it myself :)
