### ISSUE TITLE
Any way to use ocaml+flambda?

### ISSUE THREAD

**Issue by Amar1729** [timbertson/opam2nix-packages#44]
Thanks for this project, looks really cool!

I'm writing an expression for a package right now that uses an ocaml+flambda compiler (specifically, 4.06.1+flambda). Is there a way to set `ocamlAttr` to use `flambda`? I couldn't quite figure it out from reading through the nixpkgs ocaml [`generic.nix`](https://github.com/NixOS/nixpkgs/blob/ce03af969e584a199d7305c737ea1f6df5bf9d67/pkgs/development/compilers/ocaml/generic.nix).

edit - I figured out how to do it from the cli like this: `nix-shell -p ocaml --arg flambdaSupport "true"`

**Comment by timbertson** [comment]
Yeah, `ocamlAttr` is a bit lame, because it can only reference predefined derivation in `pkgs`. It's a necessary indirection when using the `opam2nix` tool on the command line, but we can do better when using the nix wrapper.

It was already possible by passing `overrides = { self, super }: { ocaml = < ... >; }` in the import phase, but that would use a different ocaml in selections vs actual import, so you'd have to be careful to also set ocamlVersion appropriately.

I've made a small change today, and as of the current master (fd06b3eb5eaefd2df470de1a646e612794df46d3) you can pass in an `ocaml` attr to `selectionsFile` (and friends). Then the version is parsed from the derivation name, and the actual derivation is baked into the selections file.

Eg. the example in `examples/opam-library/nix/default.nix` would become:

```
{ pkgs, stdenv, opam2nix }:
let ocamlPackages = pkgs.ocaml-ng.mkOcamlPackages (pkgs.callPackage <nixpkgs/pkgs/development/compilers/ocaml/4.06.nix> { flambdaSupport = true; }) (self: super: { }); in
opam2nix.buildOpamPackage rec {
	version = "0.0.1";
	name = "hello-${version}";
	src = ../.;
	ocaml = ocamlPackages.ocaml;
}
```

Thanks for motivating me to fix this ;)
